### PR TITLE
add Nullable to Schema

### PR DESCRIPTION
**Pull request by rubensayshi**
As per https://swagger.io/docs/specification/data-models/data-types/#nullable

### CODE REVIEW

**Comment by casualjim** [comment]
This is for a different spec version.
in openapi 2.0 we support x-isnullable

**Comment by rubensayshi** [comment]
> x-isnullable

I don't quite understand, it needs to go on `SwaggerSchemaProps` ?

**Comment by rubensayshi** [comment]
ah, so how can you add `x-` properties?

**Comment by casualjim** [comment]
```go
definition := getSchemaPtr()
definition.AddExtenstion("x-isnullable", true)
```

**Comment by rubensayshi** [comment]
thx @casualjim

**Pull request closed without merging**
