### PR TITLE
reference resolution 

### PR DESCRIPTION
**Pull request by kreamyx**

### CODE REVIEW

**Comment by fredbi** [comment]
I just realized you made this fix. I'll test if my testcase (issue go-swagger/go-swagger#1260) now passes. Swapping baseURI again TargetURI might been also the reason for go-swagger/go-swagger#1259 and go-swagger/go-swagger#1258 .. Thanks.

**Comment by kreamyx** [comment]
Hi @fredbi , this solves part of the problem but I am working on a more comprehensive solution. Thanks

**Comment by fredbi** [comment]
Hello Karim. I checked out your PR. It doesn't fix  go-swagger/go-swagger#1260.
Types are generated and initialized the same way.
You probably got on something, but this is not THIS particular issue.

**Comment by fredbi** [comment]
I recently posted 3 different issues regarding $ref management in general.
go-swagger/go-swagger#1258: unaffected by this PR
go-swagger/go-swagger#1259: affected by this PR but not solved. Generation now completes but generated code does not compile (generated types missing)
go-swagger/go-swagger#1260: unaffected by this PR

**Comment by fredbi** [comment]
Hello Karim. Do you need that I run my testcases again? How about integrating those as fixtures?

**Comment by kreamyx** [comment]
Hi @fredbi , I already put your tests as fixtures in go-openapi/loads ref-res branch. Expanded() expands the spec correctly but there is still an issue with code generation that I am trying to investigate

**Comment by fredbi** [comment]
OK thanks

**Pull request merged**
