### PR TITLE
introduce CommonValidations to SchemaProps.

### PR DESCRIPTION
**Pull request by takahiromiyamoto**
Hello, I want to handle Schema and Parameter in the same way. I introduced CommonValidations to SchemaProps.

### CODE REVIEW

**Comment by gregmarr** [comment]
It looks like you didn't add the new file with the `CommonValidations` type to the PR.

**Comment by fredbi** [comment]
@takahiromiyamoto 
At this moment, we carry out something similar at the codegen level in go-swagger, but not at the spec level. I am not sure this change will not break other repos. Litteral initializers, in particular, break when changing the structure this way.

**Comment by casualjim** [comment]
Yeah I don't think this is a good change. you can write type definitions that expose a common interface, or add method accessors and make an interface. But this would be a breaking change which we really want to avoid on this repo at this stage

**Comment by fredbi** [comment]
#132 works along the same line of thought, but without bringing any breaking change.
I am currently experimenting with how this may help refactor a bit codegen in go-swagger.

**Comment by fredbi** [comment]
@takahiromiyamoto this PR was very inspiring: the intent is actually sound. However, it is difficult for us to break compatibility by changing the struct members (this is probably an early design mistake, but we have to deal with it).

I leveraged your work to bring up similar capabilities thanks to an extra SchemaValidation struct. go-swagger is being refactored a bit to make use of this augmented API.

Thank you so much

Cheers,

Fred

**Pull request closed without merging**
