### PR TITLE
Fix expandSchema when basePath is empty

### LINKED ISSUE #45: Schemas are not expanded when "basePath" is empty
I think this is another regression that was introduced in #38 

Consider the following part of the schema:
```yaml
paths:
  /pet:
    post:
      tags:
      - "pet"
      summary: "Add a new pet to the store"
      operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Pet"
```

If `basePath` is empty (as I described in #44), then [this is always true](https://github.com/go-openapi/spec/blob/master/expander.go#L658), and the schema refs are never get expanded.

### PR DESCRIPTION
**Pull request by hypnoglow**
Note that **I am not sure** that this is the correct way to fix the issue (and if this fix does not break anything) because I am not familiar with #38 changes.

But at least my code that I wrote before #38 finally works after this fix.

---

Fixes #45

Signed-off-by: Igor Zibarev <zibarev.i@gmail.com>

### CODE REVIEW

**Comment by casualjim** [comment]
if you want to know if this breaks anything, you can try to run the tests in the validate package. they generally exercise most of the ref behavior

**Comment by hypnoglow** [comment]
> if you want to know if this breaks anything, you can try to run the tests in the validate package. they generally exercise most of the ref behavior

@casualjim I've run them while keeping `spec` package on this PR branch, everything seems fine.

```
~/go/src/github.com/go-openapi/validate master
ή go test -v ./...
=== RUN   TestDefaulter
--- PASS: TestDefaulter (0.00s)
	defaulter_test.go:35: Before: map[any:map[] one:map[] nested:map[] all:map[]]
	defaulter_test.go:40: After: map[one:map[bar:42] int:42 str:Hello obj:map[foo:bar] nested:map[inner:7] all:map[foo:42 bar:42] any:map[foo:42]]
=== RUN   TestNumberItemsValidation
--- PASS: TestNumberItemsValidation (0.00s)
=== RUN   TestStringItemsValidation
--- PASS: TestStringItemsValidation (0.00s)
=== RUN   TestArrayItemsValidation
--- PASS: TestArrayItemsValidation (0.00s)
=== RUN   TestItemsMustBeTypeArray
--- PASS: TestItemsMustBeTypeArray (0.00s)
=== RUN   TestItemsMustHaveType
--- PASS: TestItemsMustHaveType (0.00s)
=== RUN   TestTypeArrayMustHaveItems
--- PASS: TestTypeArrayMustHaveItems (0.00s)
=== RUN   TestNumberParameterValidation
--- PASS: TestNumberParameterValidation (0.00s)
=== RUN   TestStringParameterValidation
--- PASS: TestStringParameterValidation (0.00s)
=== RUN   TestArrayParameterValidation
--- PASS: TestArrayParameterValidation (0.00s)
=== RUN   TestExpandResponseLocalFile
--- PASS: TestExpandResponseLocalFile (1.29s)
=== RUN   TestExpandResponseRecursive
--- PASS: TestExpandResponseRecursive (1.25s)
=== RUN   TestIssue52
--- PASS: TestIssue52 (2.62s)
=== RUN   TestIssue53
--- PASS: TestIssue53 (2.63s)
=== RUN   TestIssue62
--- SKIP: TestIssue62 (0.00s)
=== RUN   TestIssue63
--- PASS: TestIssue63 (1.25s)
=== RUN   TestIssue61_MultipleRefs
--- PASS: TestIssue61_MultipleRefs (1.40s)
=== RUN   TestIssue61_ResolvedRef
--- PASS: TestIssue61_ResolvedRef (1.41s)
=== RUN   TestIssue123
--- PASS: TestIssue123 (3.05s)
=== RUN   TestIssue6
2017/12/19 10:14:20 must not validate the schema (not)
2017/12/19 10:14:20 paths./foo.get.responses in body should have at least 1 properties
2017/12/19 10:14:20 must not validate the schema (not)
2017/12/19 10:14:20 paths./foo.get.responses in body should have at least 1 properties
2017/12/19 10:14:21 paths./foo.get.responses in body is required
2017/12/19 10:14:21 paths./foo.get.responses in body is required
--- PASS: TestIssue6 (2.48s)
=== RUN   TestIssue18
2017/12/19 10:14:23 X-Foo in header has invalid pattern: ")<-- bad pattern"
2017/12/19 10:14:24 operation "" has invalid pattern in default header "X-Foo": ")<-- bad pattern"
2017/12/19 10:14:24 operation "" has invalid pattern in 402's header "X-Foo": ")<-- bad pattern"
2017/12/19 10:14:25 body param "user" for "" has invalid items pattern: ")<-- bad pattern"
2017/12/19 10:14:25 user.items in body has invalid pattern: ")<-- bad pattern"
2017/12/19 10:14:27 operation "" has invalid pattern in param "userId": ")<-- bad pattern"
2017/12/19 10:14:28 200 in response has invalid pattern: ")<-- bad pattern"
--- PASS: TestIssue18 (6.58s)
=== RUN   TestIssue39
--- PASS: TestIssue39 (1.29s)
=== RUN   TestValidateDuplicatePropertyNames
--- PASS: TestValidateDuplicatePropertyNames (0.08s)
=== RUN   TestValidateNonEmptyPathParameterNames
--- PASS: TestValidateNonEmptyPathParameterNames (0.04s)
=== RUN   TestValidateCircularAncestry
--- PASS: TestValidateCircularAncestry (0.12s)
=== RUN   TestValidateUniqueSecurityScopes
--- PASS: TestValidateUniqueSecurityScopes (0.00s)
=== RUN   TestValidateReferenced
--- PASS: TestValidateReferenced (0.07s)
=== RUN   TestValidateBodyFormDataParams
--- PASS: TestValidateBodyFormDataParams (0.04s)
=== RUN   TestValidateReferencesValid
--- PASS: TestValidateReferencesValid (0.10s)
=== RUN   TestValidatesExamplesAgainstSchema
--- PASS: TestValidatesExamplesAgainstSchema (0.16s)
=== RUN   TestValidateDefaultValueAgainstSchema
--- PASS: TestValidateDefaultValueAgainstSchema (0.87s)
=== RUN   TestValidateRequiredDefinitions
--- PASS: TestValidateRequiredDefinitions (0.04s)
=== RUN   TestValidateParameters
--- PASS: TestValidateParameters (0.17s)
=== RUN   TestValidateItems
--- PASS: TestValidateItems (0.22s)
=== RUN   TestJSONSchemaSuite
--- PASS: TestJSONSchemaSuite (0.30s)
	type_test.go:147: Running additionalItems
	type_test.go:147: Running additionalProperties
	type_test.go:147: Running allOf
	type_test.go:147: Running anyOf
	type_test.go:147: Running default
	type_test.go:147: Running definitions
	type_test.go:147: Running dependencies
	type_test.go:147: Running enum
	type_test.go:147: Running format
	type_test.go:147: Running items
	type_test.go:147: Running maxItems
	type_test.go:147: Running maxLength
	type_test.go:147: Running maxProperties
	type_test.go:147: Running maximum
	type_test.go:147: Running minItems
	type_test.go:147: Running minLength
	type_test.go:147: Running minProperties
	type_test.go:147: Running minimum
	type_test.go:147: Running multipleOf
	type_test.go:147: Running not
	type_test.go:147: Running oneOf
	type_test.go:147: Running pattern
	type_test.go:147: Running patternProperties
	type_test.go:147: Running properties
	type_test.go:147: Running ref
	type_test.go:147: Running refRemote
	type_test.go:147: Running required
	type_test.go:147: Running type
	type_test.go:147: Running uniqueItems
=== RUN   TestSchemaFixtures
--- PASS: TestSchemaFixtures (0.00s)
	type_test.go:188: Running int-enum
=== RUN   TestStringValidator_Validate_Panic
--- PASS: TestStringValidator_Validate_Panic (0.00s)
=== RUN   TestValidateIntEnum
--- PASS: TestValidateIntEnum (0.00s)
=== RUN   TestValidateEnum
--- PASS: TestValidateEnum (0.00s)
=== RUN   TestValidateUniqueItems
--- PASS: TestValidateUniqueItems (0.00s)
=== RUN   TestValidateMinLength
--- PASS: TestValidateMinLength (0.00s)
=== RUN   TestValidateMaxLength
--- PASS: TestValidateMaxLength (0.00s)
=== RUN   TestValidateRequired
--- PASS: TestValidateRequired (0.00s)
=== RUN   TestValidateRequiredNumber
--- PASS: TestValidateRequiredNumber (0.00s)
=== RUN   TestMultipleOf
--- PASS: TestMultipleOf (0.00s)
PASS
ok  	github.com/go-openapi/validate	27.533s
```

**Comment by kreamyx** [comment]
Also the tests in `go-openapi/loads` exercise a lot of $ref use cases that are not exercised in `go-openapi/validate`

I am curious to know in what circumstances did expandSchema's basepath happen to be an empty string?

**Comment by hypnoglow** [comment]
@kreamyx 
> I am curious to know in what circumstances did expandSchema's basepath happen to be an empty string?

That's the case when you store a raw spec in a variable. For example in tests or your fetch raw spec data from somewhere (weird but still we should not only rely on a spec stored in a file).

Consider the following code where you store raw spec in `jsn` variable:
```golang
doc, _ := loads.Analyzed(jsn, "2.0")
doc, _ = doc.Expanded()
validate.Spec(doc, strfmt.Default)
...
```

**Pull request merged**
